// Content: vocab/phrases = [word, pronunciation, English]; grammar = {t, e, ex:[[target, English]], q:[prompt, options, correctIndex]}
const D = {
es:{name:'Spanish',code:'es-ES',
 vocab:[['hola','OH-lah','hello'],['gracias','GRAH-syahs','thank you'],['agua','AH-gwah','water'],['casa','KAH-sah','house'],['comida','koh-MEE-dah','food'],['libro','LEE-broh','book'],['amigo','ah-MEE-goh','friend'],['gato','GAH-toh','cat'],['leche','LEH-cheh','milk'],['escuela','es-KWEH-lah','school']],
 phrases:[['¿Cómo estás?','KOH-moh es-TAHS','How are you?'],['Me llamo Ana','meh YAH-moh AH-nah','My name is Ana'],['¿Dónde está el baño?','DOHN-deh es-TAH el BAH-nyoh','Where is the bathroom?'],['Quiero un café','KYEH-roh oon kah-FEH','I would like a coffee'],['No entiendo','noh en-TYEN-doh',"I don't understand"]],
 grammar:[{t:'Gender of nouns',e:'Nouns are masculine or feminine. Use el/un with masculine nouns and la/una with feminine nouns.',ex:[['el libro','the book'],['la casa','the house']],q:['___ casa (the house)',['el','la','los','un'],1]},
  {t:'Ser vs. estar',e:'Both mean "to be". Use ser for identity and lasting traits, and estar for states and locations.',ex:[['Soy estudiante','I am a student'],['Estoy cansada','I am tired']],q:['Ella ___ cansada (she is tired)',['es','está','son','eres'],1]},
  {t:'Plurals',e:'Add -s to words ending in a vowel and -es to words ending in a consonant.',ex:[['libro, libros','book, books'],['papel, papeles','paper, papers']],q:['Plural of "libro"',['libroes','libros','libra','los libro'],1]}]},
fr:{name:'French',code:'fr-FR',
 vocab:[['bonjour','bon-ZHOOR','hello'],['merci','mehr-SEE','thank you'],['eau','oh','water'],['maison','may-ZON','house'],['pain','pan','bread'],['livre','LEEVR','book'],['ami','ah-MEE','friend'],['chat','shah','cat'],['lait','leh','milk'],['école','ay-KOL','school']],
 phrases:[['Comment ça va ?','koh-MON sah VAH','How are you?'],["Je m'appelle Léa",'zhuh mah-PEL lay-AH','My name is Léa'],['Où sont les toilettes ?','oo son lay twah-LET','Where are the restrooms?'],['Je voudrais un café','zhuh voo-DRAY uhn kah-FAY','I would like a coffee'],['Je ne comprends pas','zhuh nuh kom-PRON pah',"I don't understand"]],
 grammar:[{t:'Definite articles',e:'Use le for masculine, la for feminine, and les for plural nouns. Before a vowel, le and la become l\'.',ex:[['le livre','the book'],['la maison','the house']],q:['___ maison (the house)',['le','la','les','un'],1]},
  {t:'The verb être',e:'Être means "to be": je suis, tu es, il/elle est, nous sommes, vous êtes, ils/elles sont.',ex:[['Je suis étudiant','I am a student'],['Nous sommes amis','We are friends']],q:['Nous ___ amis (we are friends)',['suis','es','sommes','êtes'],2]},
  {t:'Negation',e:'Wrap the verb with ne ... pas to say no.',ex:[['Je ne mange pas','I do not eat'],['Il ne parle pas','He does not speak']],q:['Je ne mange ___ (I do not eat)',['pas','non','rien de','jamais pas'],0]}]},
hi:{name:'Hindi',code:'hi-IN',
 vocab:[['नमस्ते','na-mas-TEY','hello'],['धन्यवाद','dhan-ya-VAAD','thank you'],['पानी','PAA-nee','water'],['घर','ghar','house'],['खाना','KHAA-naa','food'],['किताब','ki-TAAB','book'],['दोस्त','dost','friend'],['बिल्ली','BIL-lee','cat'],['दूध','doodh','milk'],['स्कूल','skool','school']],
 phrases:[['आप कैसे हैं?','aap KAI-se hain','How are you?'],['मेरा नाम अना है','MEH-raa naam ah-NAA hai','My name is Ana'],['शौचालय कहाँ है?','shau-chaa-LAY ka-HAAN hai','Where is the restroom?'],['मुझे एक चाय चाहिए','mu-JHEY ek chaai chaa-HI-ey','I would like a tea'],['मुझे समझ नहीं आया','mu-JHEY sa-MAJH na-HEEN aa-YAA',"I don't understand"]],
 grammar:[{t:'Word order',e:'Hindi sentences usually follow subject-object-verb order, so the verb comes last.',ex:[['मैं पानी पीता हूँ','I water drink (I drink water)']],q:['In a Hindi sentence the verb usually comes...',['at the end','at the start','after the subject','anywhere'],0]},
  {t:'You: तुम vs. आप',e:'आप is the polite, respectful "you". तुम is informal and used with friends and younger people.',ex:[['आप कैसे हैं?','How are you? (polite)'],['तुम कैसे हो?','How are you? (informal)']],q:['Which word is the respectful "you"?',['तुम','आप','मैं','वह'],1]},
  {t:'है and हैं',e:'है is "is" for one person or thing. हैं is "are", and is also used for respect.',ex:[['वह घर पर है','He is at home'],['वे घर पर हैं','They are at home']],q:['वह घर पर ___ (he is at home)',['है','हैं','हूँ','हो'],0]}]}
};
